config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  resources :items do
    resources :pictures, only: [:destroy, :create, :index]
  end

  resources :bookings, except: [:index]

  devise_for :users

  get "profile" => "profile#show", as: "profile"
  get "profile/edit" => "profile#edit", as: "edit_profile"
  patch "profile" => "profile#update"

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :pictures
  has_many :bookings
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :item
  has_attached_file :file, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :firstname, :lastname, :address, :zipcode, :city, presence: true

  has_many :items
  has_many :bookings

  after_create :send_welcome_email

  def send_welcome_email
    UserMailer.welcome_email(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    %w(firstname lastname birthdate address zipcode city email).each do |field|
      devise_parameter_sanitizer.for(:sign_up) << field.to_sym
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
 before_action :set_booking, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def create
    booking = current_user.bookings.create(booking_params)
    stay_length = (booking.departure - booking.arrival).to_i
    booking.price = stay_length * booking.item.price
    redirect_to profile_path
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def booking_params
    @booking_params = params.require(:booking).permit(:item_id, :arrival, :departure)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
 before_action :set_item, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
 respond_to :js, :html

  def index
    @items = Item.all
  end

  def show
    @booking = Booking.new
  end

  def new
    @item = current_user.items.build
  end

  def create
    item = current_user.items.create(item_params)
    redirect_to item_pictures_path(item)
  end

  def edit

  end

  def update
    @item.update(item_params)
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

private

  def item_params
    @item_params = params.require(:item).permit(:price, :description, :title, :user_id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_item, only: [:index, :create]
   respond_to :js, :html

  def destroy
    Picture.find(params[:id]).destroy!
    render json: { status: 'OK' }
  end

  def index
    @picture = Picture.new
  end

  def create
    @item.pictures.create(picture_params)
    puts params

    respond_with do |format|
      format.js
      format.html { redirect_to item_path(item)}
    end
  end

  private

  def picture_params
    params.require(:item).permit(:file)
  end

  def set_item
    @item = Item.find(params[:item_id])
  end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!

  def show
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:firstname, :lastname, :address, :zipcode, :city, :birthdate)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/bookings/_form.html.erb
<%= form_for @booking do |f| %>

  <div class="form-group">
    <%= f.label :arrival, 'Arrival', class: "control-label" %>
    <%= f.date_field :arrival, value: Date.today, class: "control-label" %>
  </div>

   <div class="form-group">
    <%= f.label :departure, 'Departure', class: "control-label" %>
    <%= f.date_field :departure %>
  </div>

    <%= f.hidden_field :item_id, value: item_id %>

  <%= f.submit "Book this item", class: "btn btn-primary" %>

<% end %>

app/views/items/_announce.html.erb
<%= link_to item_path (item) do %>
  <div class="col-sm-12 col-md-6 col-xs-12">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Wrapper for slides -->
      <div class="carousel-inner" id="fix_width">
        <% item.pictures.each_with_index do |picture, index| %>
          <div class="item <%= index == 0 ? 'active' : nil %>">
            <%= image_tag picture.file.url(:medium) %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-sm-8 col-md-8 col-xs-8 bg-primary">
      <p><%= item.title %></p>
      <p><%= item.user.city %></p>
    </div>
    <div class="col-sm-4 col-md-4 col-xs-4 bg-primary text-center">
      <p><%= item.price %><%=' €'%></p>
      <p><%= 'Par jour' %></p>
    </div>

      <!-- Controls
      <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a> -->
  </div>

<% end %>

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Titre', class: "control-label" %>
    <%= f.text_field :title, class: "form-control", placeholder: "Titre" %>
  </div>
  <div class="form-group">
    <%= f.label :description, 'Description', class: "control-label" %>
    <%= f.text_field :description, class: "form-control", placeholder: "Description" %>
  </div>
  <div class="form-group">
    <%= f.label :price, 'Prix', class: "control-label" %>
    <%= f.text_field :price, class: "form-control", placeholder: "Prix" %>
  </div>

  <% f.text_field :user_id, value: current_user %>

  <%= f.submit "Submit", class: "btn btn-primary" %>

<% end %>

app/views/items/edit.html.erb
<div class="col-md-8 col-md-offset-2">

<h1>Change your Announce !</h1>

<%= render 'items/form' %>

</div>

app/views/items/index.html.erb
<div class="col-md-5 visible-lg visible-md">
  <%= image_tag("carte.png", class: "carte") %>
</div>

<div class="col-md-7 col-md-offset-5">
  <div class="row">
    <div class="col-xs-12">
      <form class="form-inline" id="button_loc" role="search">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Location">
          <span class="input-group-btn">
            <button class="btn btn-primary" type="button">Search</button>
          </span>
        </div>
      </form>
    </div>
  </div>
  <div class="row">
      <% @items.each do |item| %>
        <%= render 'items/announce', item: item %>
      <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="col-md-8 col-md-offset-2">

<h1>Créez votre annonce !</h1>

<%= render 'items/form' %>

</div>

app/views/items/show.html.erb
<div class="row">
  <div class="col-md-4">
    <h2><%= @item.title %></h2>
  </div>

  <div class="col-md-4 pull-right">
    <h2>Owner</h2>
  </div>

</div>


<div class="row">
  <div class="col-md-4">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Wrapper for slides -->
      <div class="carousel-inner" id="fix_width">
        <% @item.pictures.each_with_index do |picture, index| %>
          <div class="item <%= index == 0 ? 'active' : nil %> <%= "item#{index}"%>">
            <%= image_tag picture.file.url(:medium)%>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-3 marg-bottom">
      <% @item.pictures.each_with_index do |picture, index| %>
        <%= image_tag picture.file.url(:thumb), class: "img-thumbnail margin-thumb trigger-#{index}", id: "nopadding" %>
      <% end %>
  </div>

  <script>
    $(function(){
      $(".trigger-0").click(function(){
        $(".active").removeClass("active");
        $(".item0").addClass("active");
      });
      $(".trigger-1").click(function(){
        $(".active").removeClass("active");
        $(".item1").addClass("active");
      });
      $(".trigger-2").click(function(){
        $(".active").removeClass("active");
        $(".item2").addClass("active");
      });
      $(".trigger-3").click(function(){
        $(".active").removeClass("active");
        $(".item3").addClass("active");
      });
    })
  </script>

  <div class="col-md-4 pull-right">
    <p><%= current_user.firstname.capitalize %> <%= current_user.lastname.capitalize %></p>
    <p><%= 'From '%> <%= current_user.city %><p>
  </div>

</div>

<div class="row">

  <div class="col-md-4">
    <h2>Description</h2>
    <p><%= @item.description %><p>
  </div>


  <div class="col-md-4 pull-right">
    <section class="booking">
      <h2>Booking</h2>
      <%= render 'bookings/form', {item_id: params[:id]} %>
    </section>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <% if notice %><p class="notice"><%= notice %></p><%end%>
  <% if alert %><p class="alert"><%= alert %></p><%end%>
<head>
  <title>Kiloukoi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

</head>
<body class="align-body">

<header id="navbar-top">
  <nav id="color" class="navbar navbar-default navbar-fixed-top" role="navigation">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      <div class="navbar-header logo">
        <a><%= link_to 'KILOUKOI', root_path %></a>
      </div>

      <% if user_signed_in? %>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right align-nav">
          <li><%= link_to current_user.firstname, profile_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to 'New Announce', new_item_path %></li>
        </ul>
      </div>

      <% else %>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right align-nav">
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Log In', new_user_session_path %></li>
            <li><%= link_to 'New Announce', new_item_path %></li>
          </ul>
        </div>
      <% end %>

  </nav>
</header>

<div class="container">
<%= yield %>
</div>



</body>
</html>

app/views/pictures/_pictures.html.erb
  <% @item.pictures.each do |picture|%>
    <fieldset>
      <%= image_tag picture.file.url(:thumb) %>
      <%= link_to "Delete", item_picture_path(item_id: @item.id, id: picture.id), class: 'delete-picture', method: :delete, remote: true %>
    </fieldset>
  <% end %>

app/views/pictures/create.js.erb
$('#picture-container').html("<%= j render partial: 'pictures' %>")

app/views/pictures/edit.html.erb
<%= form_for [@item , @picture] , :html => { :multipart => true}, remote: true do |f| %>

  <div id='picture-container'>
   <%= render partial: 'pictures' %>
  </div>

  <div class="form-group">
    <%= f.label :file, 'picture', class: "control-label" %>
  </div>

  <div class="fileUpload btn btn-primary">
    <span>Upload</span>
    <input type="file" class="upload" name="item[file]" />
  </div>

<% end %>

app/views/pictures/index.html.erb
<%= form_for [@item , @picture] , :url => item_pictures_path, :html => { :multipart => true}, remote: true do |f| %>

  <div id='picture-container'>
   <%= render partial: 'pictures' %>
  </div>

  <div class="form-group">
    <%= f.label :file, 'picture', class: "control-label" %>
  </div>

  <div class="fileUpload btn btn-primary">
    <span>Upload</span>
    <input type="file" class="upload" name="item[file]" />
  </div>

<% end %>

app/views/pictures/update.js.erb
console.log('salut')
$('#picture-container').html("<%= j render partial: 'pictures' %>")